export const softwareEngineerSkills = [
  "Python",
  "JavaScript",
  "React.js",
  "Node.js",
  "SQL",
  "Git",
  "Docker",
  "AWS",
  "Unit Testing",
  "Problem Solving",
  "Software Architecture",
  "System Design",
  "API Development",
  "Microservices Architecture",
  "Security Best Practices",
  "Code Reviews",
  "Continuous Learning",
  "Project Management",
];
